### ISSUE TITLE
Card permissions cross between multiple held cards.

### ISSUE THREAD

**Issue by Oxygen556** [Parkeymon/RemoteKeycard#3]
#2 - Referencing this issue because I'm basically re-wording this but in more technical terms.

Plugin code does not check card permissions on an individual card held in inventory, but rather looks at the collective permissions of the cards in the user's inventory to check permissions - hence people can open stuff like SCP item lockers _very_ early by having a combination of keycards instead of a single keycard.

_Please fix this issue at your earliest convenience._
Oxygen, Owner & Co-Founder of [US] The Stash.

**Comment by Parkeymon** [comment]
this got fixed in a forked version but it is now fixed here, releasing soon
